#### NumPy - Numerical Python

#### Advantages of NumPy Arrays
   ##### 1.Allow Several Mathematical Operations
   ##### 2.Faster Operations

In [5]:
import numpy as np

#### List vs Numpy- Time Taken

In [25]:
from time import process_time

##### Time Taken by a list

In [26]:
python_list=[i for i in range(10000000)]

start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()

time = end_time-start_time
print(time)

0.40625


##### Time Taken by a Numpy Array

In [27]:
np_array=np.array([i for i in range(10000000)])

start_time=process_time()
np_array +=5
end_time=process_time()
np_time = end_time-start_time
print(np_time)

0.015625


### NumPy Arrays

In [28]:
   # List

list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [29]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [30]:
# Creating a one dimensional array

a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [37]:
a.shape   #(columns )

(5,)

In [34]:
# Creating a two dimensional array

b=np.array([(1,2,3,4) ,(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [36]:
b.shape    # (rows,columns)

(2, 4)

In [40]:
c=np.array([(1,2,3,4),(5,6,7,8)] ,dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


### Initial placeholders in NumPy arrays

In [41]:
# create a numpy arrays of 0s

x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [42]:
# create a numpy arrays of ones

y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
# array of a particular values
z=np.full((5,4),5)    # matric shape , value
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [45]:
# create an identity matrix

a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


###  create a numpy array with random values

In [48]:

# value with between 0 and 1
b=np.random.random((3,4))      # shape of the matric
print(b)

[[0.10884561 0.48989926 0.0428027  0.00742551]
 [0.25909898 0.04490771 0.98546369 0.26514132]
 [0.96948924 0.01122892 0.64411257 0.41977365]]


In [49]:
# random integer array within a specific range

c=np.random.randint(10,100,(3,4))     #(start value, end value, matric size)
print(c)

[[93 27 59 54]
 [85 47 56 99]
 [41 57 40 49]]


In [53]:
# array of evenly spaced values  ---> Specifying the number of values required

d=np.linspace(10,30,6)   #(start range,end range,number of values we need)
print(d)


"""
✅ 1. np.linspace(start, stop, num)
Creates num evenly spaced values between start and stop
Includes the stop value
"""

[10. 14. 18. 22. 26. 30.]


In [54]:
# array of evenly spaced values  ---> specifying the step
e=np.arange(10,30,5)   #(start range,end range,)
print(e)

"""
✅ 2. np.arange(start, stop, step)

Creates values starting at start
Increments by step
Does NOT include the stop value
Similar to Python’s range()

"""

[10 15 20 25]


### Convert a list to a numpy array

In [56]:
list2= [10,20,30,40,50]
print(list2)
print(type(list2))
np_array=np.array(list2)
print(np_array)
print(type(np_array))

[10, 20, 30, 40, 50]
<class 'list'>
[10 20 30 40 50]
<class 'numpy.ndarray'>


### Analysing a numpy aray

In [59]:
c=np.random.randint(10,90,(5,5))
print(c)

[[51 50 19 23 20]
 [60 81 50 53 74]
 [72 89 62 54 41]
 [30 84 48 30 75]
 [89 83 41 89 48]]


In [62]:
# array dimesions
print(c.shape)

(5, 5)


In [63]:
# number of dimensions
print(c.ndim)

2


In [64]:
# number of elements in an array
print(c.size)

25


In [65]:
# checking the data type of values in the array

print(c.dtype)

int32


### Mathematical operations in np array

In [66]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]

print(list1+list2)  # concatenating or joints

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [67]:
np_array_list1=np.array(list1)
np_array_list2=np.array(list2)

print(np_array_list1+np_array_list2)

[ 7  9 11 13 15]


In [68]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

print(a)
print(b)

[[2 9 6]
 [9 9 1]
 [3 5 1]]
[[19 18 18]
 [12 10 11]
 [12 15 18]]


In [70]:
print(a+b)
print()
print(a-b)
print()
print(a*b)
print()
print(a/b)

[[21 27 24]
 [21 19 12]
 [15 20 19]]

[[-17  -9 -12]
 [ -3  -1 -10]
 [ -9 -10 -17]]

[[ 38 162 108]
 [108  90  11]
 [ 36  75  18]]

[[0.10526316 0.5        0.33333333]
 [0.75       0.9        0.09090909]
 [0.25       0.33333333 0.05555556]]


In [71]:
print(np.add(a,b))

[[21 27 24]
 [21 19 12]
 [15 20 19]]


In [72]:
print(np.subtract(a,b))

[[-17  -9 -12]
 [ -3  -1 -10]
 [ -9 -10 -17]]


In [73]:
print(np.multiply(a,b))

[[ 38 162 108]
 [108  90  11]
 [ 36  75  18]]


In [74]:
print(np.divide(a,b))

[[0.10526316 0.5        0.33333333]
 [0.75       0.9        0.09090909]
 [0.25       0.33333333 0.05555556]]


### Array Manipulation

In [76]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 6 8]
 [3 1 3]]
(2, 3)


In [77]:
# transpose   - reversing the array shape

trans =np.transpose(array)
print(trans)

print(trans.shape)

[[0 3]
 [6 1]
 [8 3]]
(3, 2)


In [78]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[0 3]
 [6 1]
 [8 3]]
(3, 2)


In [79]:
# reshaping array

a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 3 1]
 [1 0 1]]
(2, 3)


In [80]:
b=a.reshape((3,2))
print(b)
print(b.shape)

[[9 3]
 [1 1]
 [0 1]]
(3, 2)
